project_id = "fgnurcnjqjbqnbdtjirv"

[functions.cleanup-old-attachments]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.update-user-credentials]
verify_jwt = true

[functions.get-user-auth-details]
verify_jwt = true