// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgnurcnjqjbqnbdtjirv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnbnVyY25qcWpicW5iZHRqaXJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzYzNDQsImV4cCI6MjA3MDI1MjM0NH0.TmG5bqOujOpF-mjPFsUYXu16O9qXFk3aF0HxtRhDZHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});